name: Hello World Service application workflow
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'pom.xml'
      - 'Dockerfile'
      - '.dockerignore'
      - 'src/**'
      - '.github/workflows/hello-world-service.yaml'

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up the Maven dependencies caching
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Maven dependencies
        run: mvn install

  docker-build:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs:
      - build-and-run-tests
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Dashboard to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ajres/hello-world-service:latest
            ajres/hello-world-service:${{ github.sha }}

  update-manifest-in-managment-repository:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        name: Changing deployment version in hello-world-service on production environment
        with:
          github-token: ${{ secrets.LOGIN_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'Piotr387',
              repo: 'hello-world-service-manifests',
              workflow_id: 'change-application-version.yaml',
              ref: 'master',
              inputs: {
                service_name: 'hello-world-service',
                image: 'ajres/hello-world-service:${{ github.sha }}',
                environment: 'production'
              }
            })